spring:
  data:
    datasource:
      driver-class-name: org.h2.Driver
      schema: classpath:/db/schema-h2.sql
      data: classpath:/db/data-h2.sql
      url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: root
      password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

  #  datasource:
  #    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://192.168.79.129:3306/cdh?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    druid:
  #      username: root
  #      password: root


  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true

#  rabbitmq:
#    addresses: 120.24.224.90:5672
#    username: admin
#    password: admin
#    virtual-host: /
#    listener:
#      direct:
#        auto-startup: true
#        missing-queues-fatal: true

server:
  port: 8080




#dubbo:
#  # 配置服务信息
#  application:
#    name: dubbo-provider
#    # 禁用QOS同一台机器可能会有端口冲突现象
#    qos-enable: false
#    qos-accept-foreign-ip: false
#  # 配置注册中心
#  registry:
#    address: nacos://120.24.224.90:8848
#  # 设置协议-协议由提供方指定消费方被动接受
#  protocol:
#    name: dubbo
#    port: 20880
